== Wattbar

Wattbar is a minimalist battery charge monitor. It simply draws the battery
level in a narrow strip along the bottom of the screen.


=== History
Wattbar is only the latest in a long line of battery monitors starting with
https://github.com/lichtblau/xbattbar[YAMAGUCHI Suguru's xbattbar] in 1998.

The original program has been updated by a number of different authors to support
more modern hardware interfaces; the original APM was already getting replaced by
ACPI in 2005, and the kernel interfaces to access ACPI information have changed
significantly in the time since. Thus, in 2015, I (TQ Hirsch) rewrote the utility
from scratch in Go; this version was called https://github.com/thequux/xbattbar3[xbattbar3];
to avoid kernel interface churn, I used UPowerd to access the battery charge status.
(For the curious, I consider the ACPI version linked above to be xbattbar2, thus the
next version is version 3)

In 2022, X has been starting to get a bit long in the tooth, and my laptop works
far better with Wayland than X. Thus, it became time to rewrite it again; this new
version needed a different name. "wbattbar" was the initial obvious choice, but
leaving out the "b" made it a better pun. Aside from the fact that it renders to
Wayland instead of X11, it should be a drop-in replacement for any of the previous
versions of xbattbar.